{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "freecelpip.fullname" . }}-keyvault
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freecelpip.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.clientId | default "" | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.keyVault.secrets }}
        {{- if .key }}
        - |
          objectName: {{ .key | quote }}
          objectType: secret
          objectAlias: {{ .name | quote }}
        {{- end }}
        {{- end }}
  secretObjects:
  - secretName: {{ include "freecelpip.fullname" . }}-kv-secrets
    type: Opaque
    data:
    {{- range .Values.keyVault.secrets }}
    {{- if .key }}
    - objectName: {{ .name | quote }}
      key: {{ .name | quote }}
    {{- end }}
    {{- end }}
{{- end }}
